In [ ]:
# 합성곱
# convolution
# 칸벌루션
# 커널
# 바이어스

In [23]:
import numpy as np
import cv2

arr1 = np.random.randint(0, 10, size=(3, 3)).astype(np.float32)
arr2 = np.random.randint(0, 10, size=(3, 3))
arr3 = np.random.randint(0, 10, size=(3, 3))
kernel = np.array([[0, -1, 0],
                   [-1, 5,-1],
                   [0, -1, 0]]).astype(np.float32)
filtered_img = cv2.filter2D(arr1, -1, kernel)
print(arr1,'\n', filtered_img)

[[7. 2. 2.]
 [6. 2. 7.]
 [5. 1. 4.]] 
 [[19. -3. -8.]
 [14. -6. 25.]
 [11. -8.  4.]]


In [11]:
import cv2
import numpy as np

# 이미지를 그레이스케일로 읽어옵니다
img = cv2.imread('C:\source\kamp_ex\image\KEMP_IMG_DATA_Error_2.png', cv2.IMREAD_GRAYSCALE)

# 3x3 샤프닝 필터를 정의합니다
kernel = np.array([[0, -1, 0],
                   [-1, 5,-1],
                   [0, -1, 0]])

# 필터를 이미지에 적용하여 합성곱 연산을 수행합니다
filtered_img = cv2.filter2D(img, -1, kernel)
# filtered_img = cv2.filter2D(filtered_img, -1, kernel)
# filtered_img = cv2.filter2D(filtered_img, -1, kernel)
# filtered_img = cv2.filter2D(filtered_img, -1, kernel)
# 결과 이미지를 출력합니다
cv2.imshow('Filtered Image', filtered_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [6]:
import cv2
import numpy as np

# 이미지 불러오기
img = cv2.imread('C:\source\kamp_ex\image\KEMP_IMG_DATA_Error_2.png', cv2.IMREAD_GRAYSCALE)

# 소벨 필터 적용 - 수평 경계 (dx=1, dy=0)
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)

# 소벨 필터 적용 - 수직 경계 (dx=0, dy=1)
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

# 수평 및 수직 경계를 결합
sobel_combined = cv2.magnitude(sobelx, sobely)

# 결과 출력
cv2.imshow('Original Image', img)
cv2.imshow('Sobel X', sobelx)
cv2.imshow('Sobel Y', sobely)
cv2.imshow('Sobel Combined', sobel_combined)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [14]:
# np.ones((3,3), np.float32) / 9
import cv2
import numpy as np

# 이미지를 그레이스케일로 읽어옵니다
img = cv2.imread('C:\source\kamp_ex\image\KEMP_IMG_DATA_Error_2.png', cv2.IMREAD_GRAYSCALE)


kernel = np.ones((3,3), np.float32) / 9

# 필터를 이미지에 적용하여 합성곱 연산을 수행합니다
filtered_img = cv2.filter2D(img, -1, kernel)
# filtered_img = cv2.filter2D(filtered_img, -1, kernel)
# filtered_img = cv2.filter2D(filtered_img, -1, kernel)
# filtered_img = cv2.filter2D(filtered_img, -1, kernel)
# 결과 이미지를 출력합니다
cv2.imshow('Filtered Image', filtered_img)
cv2.waitKey(0)
cv2.destroyAllWindows()