In [ ]:
# numpy
# pip install numpy

In [21]:
import numpy as np
arr = np.array([1, 'two', 3]) # 배열은 값의 타입을 통일한다. 문자열이 포함되면 모두 문자열로 한다
arr1 = np.array([1, 2.0, 3]) # 실수가 포함 되면 모두 실수로 한다.
arr2 = np.array([1, 2, False]) # bool < int < float < str  큰거 위주로 통일 된다.
print(arr, arr1, arr2)
arr = np.array([1,2,3])
print(arr.shape) # shape 쉐잎 형태 면행열
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape) # 형태 면행열
arr = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print(arr.shape) # 형태 면행열
print(type(arr))
print(np.__version__)

['1' 'two' '3'] [1. 2. 3.] [1 2 0]
(3,)
(2, 3)
(2, 2, 3)
<class 'numpy.ndarray'>
2.0.1


In [20]:
import numpy as np
print(np.array((1,2,3)))
print(np.array({1,2,3}))
print(np.array({1:1,2:2,3:3}))
print(np.arange(11), np.arange(10,-1,-1)) # range 와 같은데 리스트로 반환한다.

[1 2 3]
{1, 2, 3}
{1: 1, 2: 2, 3: 3}
[ 0  1  2  3  4  5  6  7  8  9 10] [10  9  8  7  6  5  4  3  2  1  0]


1. 기본 데이터 타입
- int: 정수 데이터 타입

- np.int8: 8비트 정수 (-128 ~ 127)
- np.int16: 16비트 정수 (-32,768 ~ 32,767)
- np.int32: 32비트 정수 (-2,147,483,648 ~ 2,147,483,647)
- np.int64: 64비트 정수 (-9,223,372,036,854,775,808 ~ 9,223,372,036,854,775,807)
- uint: 부호 없는 정수 데이터 타입

- np.uint8: 8비트 부호 없는 정수 (0 ~ 255)
- np.uint16: 16비트 부호 없는 정수 (0 ~ 65,535)
- np.uint32: 32비트 부호 없는 정수 (0 ~ 4,294,967,295)
- np.uint64: 64비트 부호 없는 정수 (0 ~ 18,446,744,073,709,551,615)
- float: 부동 소수점 데이터 타입

- np.float16: 16비트 부동 소수점 수
- np.float32: 32비트 부동 소수점 수
- np.float64: 64비트 부동 소수점 수 (일반적으로 float의 기본 타입)
- complex: 복소수 데이터 타입

- np.complex64: 64비트 복소수 (32비트 실수부 + 32비트 허수부)
- np.complex128: 128비트 복소수 (64비트 실수부 + 64비트 허수부)
2. 문자열 데이터 타입
- string: 문자열 데이터 타입
- np.str_: 문자열
- np.bytes_: 바이트 문자열
3. 불리언 데이터 타입
- bool: 불리언 데이터 타입
- np.bool_: True 또는 False 값을 가질 수 있는 데이터 타입
4. 오브젝트 데이터 타입
- object: 일반 Python 객체를 저장할 수 있는 데이터 타입
- np.object_: 다양한 데이터 타입을 저장할 수 있습니다.
5. 날짜와 시간 데이터 타입
- datetime: 날짜 및 시간 관련 데이터 타입
- np.datetime64: 날짜 및 시간을 저장하는 데 사용됩니다.
- np.timedelta64: 시간 차이를 나타내는 데 사용됩니다.

In [28]:
import numpy as np
print(len(np.linspace(1,10))) # 기본적으로 50개의 요소로 된 배열을 준다. 
print(np.linspace(1,10, num=10)) # 기본 float 타입
print(np.zeros((2,2)), np.ones((2,2)), sep='\n')

50
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
