In [1]:
import numpy as np
import tensorflow as tf

In [13]:
import numpy as np
import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
Dense = tf.keras.layers.Dense
Sequential = tf.keras.models.Sequential
import os

def clear_screen():
    # 운영체제에 따라 화면을 지우는 명령어 선택
    os.system('cls' if os.name == 'nt' else 'clear')
from IPython.display import clear_output

# print('1번')
# clear_output(wait=True)  # 출력 지우기
# print('2번')
# print('1번')
# clear_screen()  # 화면 지우기
# print('2번')
# OR 연산을 위한 입력 데이터와 레이블
# 입력 데이터: 2차원 배열, 각 행은 OR 연산의 입력
# 출력 데이터: OR 연산의 결과
x_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = np.array([[0], [1], [1], [1]])

# 모델 생성
model = Sequential()
#기본적으로 Dense 레이어는 편향을 포함하도록 설계되어 있습니다. 즉, 편향이 자동으로 추가되므로 명시적으로 입력 뉴런의 수에 편향 뉴런을 포함시킬 필요는 없습니다.
# input_dim 입력층 구멍 개수
model.add(Dense(1, input_dim=2, activation='sigmoid'))  # 1개의 뉴런을 가진 출력층, sigmoid 활성화 함수

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 모델 훈련
# model.fit(x_train, y_train, epochs=1000, verbose=0)  # 100번의 epoch 동안 훈련
# verbose=0: 학습 중에 아무런 출력도 표시하지 않습니다.
# verbose=1: 학습의 진행 상황을 표시합니다. 각 에포크(epoch)에 대해 진행 막대(progress bar)와 함께 손실(loss) 및 정확도(accuracy) 등이 표시됩니다.
epochs = 10000
for epoch in range(epochs):
    history = model.fit(x_train, y_train, epochs=1, verbose=1)
    # 가중치와 편향 출력
    weights, biases = model.layers[0].get_weights()
    clear_output(wait=True) # clear_screen()
    print("가중치 (Weights):\n", weights)
    print("편향 (Biases):\n", biases)
    accuracy = history.history['accuracy'][0]
    print("정확도 (Biases):\n", accuracy)
    if accuracy == 1.0 and epochs > 100 :
        print(f"정확도가 100%에 도달한 에포크: {epoch + 1}")
        break
# 모델 평가
loss, accuracy = model.evaluate(x_train, y_train)
print(f'Accuracy: {accuracy * 100:.2f}%')

# 예측
predictions = model.predict(x_train)
print('Predictions:')
print(np.round(predictions))  # 예측 결과를 0 또는 1로 반올림하여 출력




# 모델 저장
# model.save('my_model.keras')  # HDF5 포맷으로 저장
# from tensorflow.keras.models import load_model

# # 저장된 모델 불러오기
# model = load_model('my_model.keras')

# # 불러온 모델로 예측 수행
# predictions = model.predict(x_test)
#.h5 확장자는 HDF5(Hierarchical Data Format version 5) 파일 포맷


# from keras.callbacks import EarlyStopping

# # Early stopping 설정
# early_stopping = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

# # 모델 훈련
# model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping])


가중치 (Weights):
 [[1.9349151]
 [1.2326565]]
편향 (Biases):
 [-0.00072642]
정확도 (Biases):
 1.0
정확도가 100%에 도달한 에포크: 3700
1/1 [==============================] - 0s 98ms/step - loss: 0.2813 - accuracy: 1.0000
Accuracy: 100.00%
1/1 [==============================] - 0s 39ms/step
Predictions:
[[0.]
 [1.]
 [1.]
 [1.]]


In [15]:
model.save('or_oper.keras')

In [19]:
predictions = model.predict(x_train)
print('Predictions:')
print(np.round(predictions))

1/1 [==============================] - 0s 21ms/step
Predictions:
[[0.]
 [1.]
 [1.]
 [1.]]


In [22]:
import cv2 as cv
cv.__version__
img = cv.imread(f'C:\source\exercise\image\강사 윤기원.png')
cv.imshow('img', img)
cv.waitKey()
cv.destroyAllWindows()