In [1]:
import tensorflow as tf

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 15s 1us/step


In [6]:
print(x_train.shape)
print(y_train.shape)
print(y_train[0])

(60000, 28, 28)
(60000,)
5


In [7]:
import pandas as pd
Sequential = tf.keras.Sequential # 모델
Dense = tf.keras.layers.Dense # 뉴런
models = tf.keras.models
layers = tf.keras.layers
from IPython.display import clear_output
from sklearn.model_selection import train_test_split
import sklearn as sl
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
matplotlib.rc('font', family='gulim') # NanumGothic  gulim NanumSquareRoundR

ModuleNotFoundError: No module named 'sklearn'

In [60]:
import tensorflow as tf
models = tf.keras.models
layers = tf.keras.layers
Precision = tf.keras.metrics.Precision
Recall = tf.keras.metrics.Recall
AUC = tf.keras.metrics.AUC
ModelCheckpoint = tf.keras.callbacks.ModelCheckpoint
EarlyStopping = tf.keras.callbacks.EarlyStopping
# MNIST 데이터셋 로드
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# 데이터 정규화 (0~255 범위의 픽셀 값을 0~1 사이로 변환)
x_train, x_test = x_train / 255.0, x_test / 255.0
print(type(x_train))
# 간단한 CNN 모델 정의
model = models.Sequential([
    layers.Conv2D(28, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    # layers.Dropout(0.5),
    layers.Conv2D(28, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    
    layers.Dense(392, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(196, activation='relu'),
    layers.Dropout(0.1),
    layers.Dense(10, activation='softmax')
])

# 모델 컴파일
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy']
)

# 모델 훈련
history = model.fit(x_train, y_train, epochs=50, validation_data=(x_test, y_test))

<class 'numpy.ndarray'>
Epoch 1/50
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1809 - accuracy: 0.9427 - val_loss: 0.0497 - val_accuracy: 0.9839
Epoch 2/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0668 - accuracy: 0.9801 - val_loss: 0.0464 - val_accuracy: 0.9852
Epoch 3/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0498 - accuracy: 0.9845 - val_loss: 0.0440 - val_accuracy: 0.9855
Epoch 4/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0425 - accuracy: 0.9874 - val_loss: 0.0377 - val_accuracy: 0.9890
Epoch 5/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0377 - accuracy: 0.9885 - val_loss: 0.0349 - val_accuracy: 0.9902
Epoch 6/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0318 - accuracy: 0.9898 - val_loss: 0.0285 - val_accuracy: 0.9922
Epoch 7/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0275 - accuracy: 0.9916 - val_loss

In [62]:
model.summary()

Model: "sequential_41"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_78 (Conv2D)          (None, 26, 26, 28)        280       
                                                                 
 max_pooling2d_78 (MaxPoolin  (None, 13, 13, 28)       0         
 g2D)                                                            
                                                                 
 conv2d_79 (Conv2D)          (None, 11, 11, 28)        7084      
                                                                 
 max_pooling2d_79 (MaxPoolin  (None, 5, 5, 28)         0         
 g2D)                                                            
                                                                 
 flatten_41 (Flatten)        (None, 700)               0         
                                                                 
 dense_115 (Dense)           (None, 392)             

In [61]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 예측 수행
y_pred = model.predict(x_test)

# 분류 문제인 경우: 예측 클래스 라벨 얻기
y_pred_classes = np.argmax(y_pred, axis=1)

# 실제 레이블과 예측된 라벨 비교
accuracy = accuracy_score(y_test, y_pred_classes)
print("Accuracy:", accuracy)

# 분류 보고서 출력
report = classification_report(y_test, y_pred_classes)
print("Classification Report:\n", report)

# 혼동 행렬 출력
conf_matrix = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.9912
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      1.00      1.00      1135
           2       1.00      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       0.99      0.99      0.99       958
           7       0.98      1.00      0.99      1028
           8       1.00      0.99      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

Confusion Matrix:
 [[ 976    0    0    0    0    0    3    1    0    0]
 [   0 1134    0    0    0    0    0    1    0    0]
 [   2    1 1020    2    0    0    0    7    0    0]
 [   0    0    0 1004 

In [13]:
history.history

{'loss': [0.1535910815000534],
 'accuracy': [0.9523500204086304],
 'val_loss': [0.05092945322394371],
 'val_accuracy': [0.984000027179718]}

In [7]:
Precision()

In [ ]:
import tensorflow as tf
from tensorflow.keras.metrics import Precision, Recall, AUC
Precision = tf.keras.metrics.Precision
Recall = tf.keras.metrics.Recall
AUC = tf.keras.metrics.AUC
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy', Precision(), Recall(), AUC()]
)


In [ ]:
# EarlyStopping 콜백 설정
early_stopping_cb = EarlyStopping(
    monitor='val_loss',            # 모니터링할 지표
    patience=3,                    # 성능 개선이 없더라도 기다릴 에폭 수
    restore_best_weights=True,     # 학습 중 최상의 가중치 복원
    verbose=1                      # 로그 출력 여부
)

# 모델 학습
history = model.fit(
    x_train, y_train,
    epochs=50,
    validation_data=(x_val, y_val),
    callbacks=[early_stopping_cb]  # 콜백 추가
)

In [ ]:
# ModelCheckpoint 콜백 설정
checkpoint_cb = ModelCheckpoint(
    'model_checkpoint.h5',        # 모델을 저장할 파일 경로
    save_best_only=True,            # 가장 좋은 성능의 모델만 저장
    monitor='val_loss',            # 모니터링할 지표
    mode='min',                    # 'min' 또는 'max' (val_loss의 경우 'min')
    verbose=1                      # 로그 출력 여부
)

# 모델 학습
history = model.fit(
    x_train, y_train,
    epochs=10,
    validation_data=(x_val, y_val),
    callbacks=[checkpoint_cb]      # 콜백 추가
)

In [3]:
28* 28


784